---
app/views/articles/_form.html.erb:
- sha256-q7vWWNA/q+JKgLk6dsHoicMB4yUvFZdhedorS6cR8lg=
- sha256-/L1G5RlAG0r8FKCgZL/QdzFNYA7qJf7EMW1Zzfpo5ZA=
- sha256-UciGYnO8+ceanxsqDylv4qDwuyVvapo7KA8/PxWhMZ4=
app/views/articles/index.html.erb:
- sha256-I9hQB4BM1ypsH3fDmkNSuI2/Gbo9CucjPXYeZnwgw7w=
app/templates/articles/edit.mustache:
- sha256-+7mij1/uCwtCQRWrof2NmOln5qX+5WdVwTLMpi8nuoA=
- sha256-Ny4TRIhhFpnYnSeKC274P6bfAz4TOkezLabavIAU4dA=
- sha256-I5e58Gqbu4WpO9dck18QxO7aYOHKrELIi70it4jIPi0=
- sha256-Po4LMynwnAJHxiTp3DQaQ3YDBj3paN/xrDoKl4OyxY4=
