---
app/views/articles/_form.html.erb:
- sha256-q7vWWNA/q+JKgLk6dsHoicMB4yUvFZdhedorS6cR8lg=
- sha256-/L1G5RlAG0r8FKCgZL/QdzFNYA7qJf7EMW1Zzfpo5ZA=
- sha256-UciGYnO8+ceanxsqDylv4qDwuyVvapo7KA8/PxWhMZ4=
app/views/articles/index.html.erb:
- sha256-DZ3NmGX3tMfdQaxm/q4EOyMiHhsIRJ/veXGlE6/yZzE=
- sha256-RRGPJcTnaNerYnL+cQ7W1j3MmXcfctYEQsiS0rxtsog=
- sha256-tuOLErk2A9nYoOxMH2DyGikTyWr+QV+OgFWrbKfta54=
app/views/layouts/application.html.erb:
- sha256-GqciIz7lqDMORmLzpkKYeR5vdKLlUnDPTePxdzFqDos=
app/templates/articles/edit.mustache:
- sha256-+7mij1/uCwtCQRWrof2NmOln5qX+5WdVwTLMpi8nuoA=
- sha256-Ny4TRIhhFpnYnSeKC274P6bfAz4TOkezLabavIAU4dA=
- sha256-I5e58Gqbu4WpO9dck18QxO7aYOHKrELIi70it4jIPi0=
- sha256-Po4LMynwnAJHxiTp3DQaQ3YDBj3paN/xrDoKl4OyxY4=
