---
app/views/articles/_form.html.erb:
- /L1G5RlAG0r8FKCgZL/QdzFNYA7qJf7EMW1Zzfpo5ZA=
- UciGYnO8+ceanxsqDylv4qDwuyVvapo7KA8/PxWhMZ4=
app/templates/articles/edit.mustache:
- q9v3Bg443U/XrQBBfFmcjPuruIrh4fMlKZKtygooOro=
- I5e58Gqbu4WpO9dck18QxO7aYOHKrELIi70it4jIPi0=
- Po4LMynwnAJHxiTp3DQaQ3YDBj3paN/xrDoKl4OyxY4=
