app/views/articles/_form.html.erb:
  - ZmNiZDQ2ZTUxOTQwMWI0YWZjMTRhMGEwNjRiZmQwNzczMTRkNjAwZWVhMjVmZWM0MzE2ZDU5Y2RmYTY4ZTU5MA==
  - NTFjODg2NjI3M2JjZjljNzlhOWYxYjJhMGYyOTZmZTJhMGYwYmIyNTZmNmE5YTNiMjgwZjNmM2YxNWExMzE5ZQ==
